//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackaGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.CityOrganizers = new HashSet<CityOrganizer>();
            this.CitySponsors = new HashSet<CitySponsor>();
            this.Events = new HashSet<Event>();
            this.Teams = new HashSet<Team>();
        }
    
        public int Id { get; set; }
        public string CityName { get; set; }
        public string DomainName { get; set; }
    
        public virtual ICollection<CityOrganizer> CityOrganizers { get; set; }
        public virtual ICollection<CitySponsor> CitySponsors { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
