//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackaGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventComments = new HashSet<EventComment>();
            this.EventLikes = new HashSet<EventLike>();
            this.EventMembers = new HashSet<EventMember>();
            this.EventSponsors = new HashSet<EventSponsor>();
            this.Galleries = new HashSet<Gallery>();
            this.News = new HashSet<News>();
        }
    
        public int Id { get; set; }
        public int CityId { get; set; }
        public int CreaterUserId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Text { get; set; }
        public string Address { get; set; }
        public Nullable<double> XMapPath { get; set; }
        public Nullable<double> YMapPath { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime EventDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<EventComment> EventComments { get; set; }
        public virtual ICollection<EventLike> EventLikes { get; set; }
        public virtual ICollection<EventMember> EventMembers { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<EventSponsor> EventSponsors { get; set; }
        public virtual ICollection<Gallery> Galleries { get; set; }
        public virtual ICollection<News> News { get; set; }
    }
}
