//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackaGlobal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HackaDbEntities : DbContext
    {
        public HackaDbEntities()
            : base("name=HackaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CityOrganizer> CityOrganizers { get; set; }
        public virtual DbSet<CitySponsor> CitySponsors { get; set; }
        public virtual DbSet<EventComment> EventComments { get; set; }
        public virtual DbSet<EventLike> EventLikes { get; set; }
        public virtual DbSet<EventMember> EventMembers { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventSponsor> EventSponsors { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsComment> NewsComments { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamUser> TeamUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
