//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackaGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsComment
    {
        public NewsComment()
        {
            this.NewsComments1 = new HashSet<NewsComment>();
        }
    
        public int Id { get; set; }
        public int NewsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AnswerToCommentId { get; set; }
        public string Text { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public bool IsConfirmed { get; set; }
    
        public virtual News News { get; set; }
        public virtual ICollection<NewsComment> NewsComments1 { get; set; }
        public virtual NewsComment NewsComment1 { get; set; }
        public virtual User User { get; set; }
    }
}
