//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackaGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.EventMembers = new HashSet<EventMember>();
            this.TeamUsers = new HashSet<TeamUser>();
        }
    
        public int Id { get; set; }
        public int CityId { get; set; }
        public string TeamName { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<EventMember> EventMembers { get; set; }
        public virtual ICollection<TeamUser> TeamUsers { get; set; }
    }
}
