//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackaGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CityOrganizers = new HashSet<CityOrganizer>();
            this.EventComments = new HashSet<EventComment>();
            this.EventLikes = new HashSet<EventLike>();
            this.EventMembers = new HashSet<EventMember>();
            this.Events = new HashSet<Event>();
            this.News = new HashSet<News>();
            this.NewsComments = new HashSet<NewsComment>();
            this.TeamUsers = new HashSet<TeamUser>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Picture { get; set; }
        public byte Type { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string Github { get; set; }
    
        public virtual ICollection<CityOrganizer> CityOrganizers { get; set; }
        public virtual ICollection<EventComment> EventComments { get; set; }
        public virtual ICollection<EventLike> EventLikes { get; set; }
        public virtual ICollection<EventMember> EventMembers { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<NewsComment> NewsComments { get; set; }
        public virtual ICollection<TeamUser> TeamUsers { get; set; }
    }
}
