//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackaGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitySponsor
    {
        public int Id { get; set; }
        public int CityId { get; set; }
        public string SponsorName { get; set; }
        public string SponsorWebsite { get; set; }
        public string Picture { get; set; }
        public Nullable<byte> Sort { get; set; }
    
        public virtual City City { get; set; }
    }
}
