//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackaGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.NewsComments = new HashSet<NewsComment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public int WriterUserId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string Picture { get; set; }
        public System.DateTime WriteDate { get; set; }
        public string KeywordsTag { get; set; }
        public string DescriptionTag { get; set; }
        public string Url { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<NewsComment> NewsComments { get; set; }
    }
}
