//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackaGlobal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string ContactUsPageText { get; set; }
        public string AboutUsPageText { get; set; }
        public string WebsiteTitle { get; set; }
        public string WebsiteFooter { get; set; }
        public string SmtpEmailServer { get; set; }
        public string Email { get; set; }
        public string EmailPassword { get; set; }
        public string EmailSenderName { get; set; }
    }
}
